EMBEDDING_VECTOR_SIZE = 1536

EMBEDDING_MODEL = "text-embedding-ada-002"
#EMBEDDING_MODEL = "text-embedding-3-large

LLM_MODEL = "gpt-3.5-turbo"
#LLM_MODEL = "gpt-4-turbo"

PINECONE_INDEX_NAME = "dreamsdb"
THEME_SEED_COUNT = 20
THEME_SEEDS_WEIGHT = 0.5

NOVELTY_WEIGHT = 0.4
MARKET_WEIGHT = 0.15
USEFULNESS_WEIGHT = 0.15
IMPLEMENTATION_WEIGHT = 0.15
IMPACT_WEIGHT = 0.15

MAX_ITERATIONS = 1